### ISSUE TITLE
Upcoming Release xtevent 2.0.0

### ISSUE THREAD

**Issue by jorpppp** [JMSLab/xtevent#47]
We only have a few pending issues before the release. According to SemVer, the version number for this release should be 2.0.0 

- [x] Check merging conflicts in #10 and merge the PR
- [x] Start a PR for #42 and merge
- [x] Fix the bug in #46
